'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace UmidService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="UmidServicePortBinding", [Namespace]:="http://service/")>  _
    Partial Public Class UmidService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private isWithUMIDSSIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isSSSMemberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertGSISUmidOperationCompleted As System.Threading.SendOrPostCallback
        
        Private isCsnExistOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SSIT_SERVER.My.MySettings.Default.SSIT_SERVER_UmidService_UmidService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event isWithUMIDSSIDCompleted As isWithUMIDSSIDCompletedEventHandler
        
        '''<remarks/>
        Public Event isSSSMemberCompleted As isSSSMemberCompletedEventHandler
        
        '''<remarks/>
        Public Event insertGSISUmidCompleted As insertGSISUmidCompletedEventHandler
        
        '''<remarks/>
        Public Event isCsnExistCompleted As isCsnExistCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service/", ResponseNamespace:="http://service/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isWithUMIDSSID(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssnumber As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal wsUser As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webserviceResponse
            Dim results() As Object = Me.Invoke("isWithUMIDSSID", New Object() {ssnumber, wsUser, authToken})
            Return CType(results(0),webserviceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isWithUMIDSSIDAsync(ByVal ssnumber As String, ByVal wsUser As String, ByVal authToken As String)
            Me.isWithUMIDSSIDAsync(ssnumber, wsUser, authToken, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isWithUMIDSSIDAsync(ByVal ssnumber As String, ByVal wsUser As String, ByVal authToken As String, ByVal userState As Object)
            If (Me.isWithUMIDSSIDOperationCompleted Is Nothing) Then
                Me.isWithUMIDSSIDOperationCompleted = AddressOf Me.OnisWithUMIDSSIDOperationCompleted
            End If
            Me.InvokeAsync("isWithUMIDSSID", New Object() {ssnumber, wsUser, authToken}, Me.isWithUMIDSSIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnisWithUMIDSSIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.isWithUMIDSSIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isWithUMIDSSIDCompleted(Me, New isWithUMIDSSIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service/", ResponseNamespace:="http://service/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isSSSMember(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal crn As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dob As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal givnm As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal midnm As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal surnm As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal extnm As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webserviceResponse
            Dim results() As Object = Me.Invoke("isSSSMember", New Object() {authToken, crn, dob, givnm, midnm, surnm, extnm})
            Return CType(results(0),webserviceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isSSSMemberAsync(ByVal authToken As String, ByVal crn As String, ByVal dob As String, ByVal givnm As String, ByVal midnm As String, ByVal surnm As String, ByVal extnm As String)
            Me.isSSSMemberAsync(authToken, crn, dob, givnm, midnm, surnm, extnm, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isSSSMemberAsync(ByVal authToken As String, ByVal crn As String, ByVal dob As String, ByVal givnm As String, ByVal midnm As String, ByVal surnm As String, ByVal extnm As String, ByVal userState As Object)
            If (Me.isSSSMemberOperationCompleted Is Nothing) Then
                Me.isSSSMemberOperationCompleted = AddressOf Me.OnisSSSMemberOperationCompleted
            End If
            Me.InvokeAsync("isSSSMember", New Object() {authToken, crn, dob, givnm, midnm, surnm, extnm}, Me.isSSSMemberOperationCompleted, userState)
        End Sub
        
        Private Sub OnisSSSMemberOperationCompleted(ByVal arg As Object)
            If (Not (Me.isSSSMemberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isSSSMemberCompleted(Me, New isSSSMemberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service/", ResponseNamespace:="http://service/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertGSISUmid( _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal transno As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal agncy_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssnum As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal crnum As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal dobth As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal givnm As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal midnm As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal surnm As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal extnm As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal gender As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal post_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal coun_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal provc As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal twnct As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal brgay As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal subdv As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal street As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal houblk As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rmunit As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal pob_city As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal pob_prov As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal pob_cncd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal mstat As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal givnm_fa As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal midnm_fa As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal surnm_fa As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal extnm_fa As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal givnm_mo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal midnm_mo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal surnm_mo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal extnm_mo As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal lprif_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rprif_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal lbkuf_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal rbkuf_cd As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal height As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal weight As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal disftr As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal tinum As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal cstat As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal cc_date As String,  _
                    <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webserviceResponse
            Dim results() As Object = Me.Invoke("insertGSISUmid", New Object() {transno, agncy_cd, ssnum, crnum, dobth, givnm, midnm, surnm, extnm, gender, post_cd, coun_cd, provc, twnct, brgay, subdv, street, houblk, rmunit, pob_city, pob_prov, pob_cncd, mstat, givnm_fa, midnm_fa, surnm_fa, extnm_fa, givnm_mo, midnm_mo, surnm_mo, extnm_mo, lprif_cd, rprif_cd, lbkuf_cd, rbkuf_cd, height, weight, disftr, tinum, cstat, cc_date, authToken})
            Return CType(results(0),webserviceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertGSISUmidAsync( _
                    ByVal transno As String,  _
                    ByVal agncy_cd As String,  _
                    ByVal ssnum As String,  _
                    ByVal crnum As String,  _
                    ByVal dobth As String,  _
                    ByVal givnm As String,  _
                    ByVal midnm As String,  _
                    ByVal surnm As String,  _
                    ByVal extnm As String,  _
                    ByVal gender As String,  _
                    ByVal post_cd As String,  _
                    ByVal coun_cd As String,  _
                    ByVal provc As String,  _
                    ByVal twnct As String,  _
                    ByVal brgay As String,  _
                    ByVal subdv As String,  _
                    ByVal street As String,  _
                    ByVal houblk As String,  _
                    ByVal rmunit As String,  _
                    ByVal pob_city As String,  _
                    ByVal pob_prov As String,  _
                    ByVal pob_cncd As String,  _
                    ByVal mstat As String,  _
                    ByVal givnm_fa As String,  _
                    ByVal midnm_fa As String,  _
                    ByVal surnm_fa As String,  _
                    ByVal extnm_fa As String,  _
                    ByVal givnm_mo As String,  _
                    ByVal midnm_mo As String,  _
                    ByVal surnm_mo As String,  _
                    ByVal extnm_mo As String,  _
                    ByVal lprif_cd As String,  _
                    ByVal rprif_cd As String,  _
                    ByVal lbkuf_cd As String,  _
                    ByVal rbkuf_cd As String,  _
                    ByVal height As String,  _
                    ByVal weight As String,  _
                    ByVal disftr As String,  _
                    ByVal tinum As String,  _
                    ByVal cstat As String,  _
                    ByVal cc_date As String,  _
                    ByVal authToken As String)
            Me.insertGSISUmidAsync(transno, agncy_cd, ssnum, crnum, dobth, givnm, midnm, surnm, extnm, gender, post_cd, coun_cd, provc, twnct, brgay, subdv, street, houblk, rmunit, pob_city, pob_prov, pob_cncd, mstat, givnm_fa, midnm_fa, surnm_fa, extnm_fa, givnm_mo, midnm_mo, surnm_mo, extnm_mo, lprif_cd, rprif_cd, lbkuf_cd, rbkuf_cd, height, weight, disftr, tinum, cstat, cc_date, authToken, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertGSISUmidAsync( _
                    ByVal transno As String,  _
                    ByVal agncy_cd As String,  _
                    ByVal ssnum As String,  _
                    ByVal crnum As String,  _
                    ByVal dobth As String,  _
                    ByVal givnm As String,  _
                    ByVal midnm As String,  _
                    ByVal surnm As String,  _
                    ByVal extnm As String,  _
                    ByVal gender As String,  _
                    ByVal post_cd As String,  _
                    ByVal coun_cd As String,  _
                    ByVal provc As String,  _
                    ByVal twnct As String,  _
                    ByVal brgay As String,  _
                    ByVal subdv As String,  _
                    ByVal street As String,  _
                    ByVal houblk As String,  _
                    ByVal rmunit As String,  _
                    ByVal pob_city As String,  _
                    ByVal pob_prov As String,  _
                    ByVal pob_cncd As String,  _
                    ByVal mstat As String,  _
                    ByVal givnm_fa As String,  _
                    ByVal midnm_fa As String,  _
                    ByVal surnm_fa As String,  _
                    ByVal extnm_fa As String,  _
                    ByVal givnm_mo As String,  _
                    ByVal midnm_mo As String,  _
                    ByVal surnm_mo As String,  _
                    ByVal extnm_mo As String,  _
                    ByVal lprif_cd As String,  _
                    ByVal rprif_cd As String,  _
                    ByVal lbkuf_cd As String,  _
                    ByVal rbkuf_cd As String,  _
                    ByVal height As String,  _
                    ByVal weight As String,  _
                    ByVal disftr As String,  _
                    ByVal tinum As String,  _
                    ByVal cstat As String,  _
                    ByVal cc_date As String,  _
                    ByVal authToken As String,  _
                    ByVal userState As Object)
            If (Me.insertGSISUmidOperationCompleted Is Nothing) Then
                Me.insertGSISUmidOperationCompleted = AddressOf Me.OninsertGSISUmidOperationCompleted
            End If
            Me.InvokeAsync("insertGSISUmid", New Object() {transno, agncy_cd, ssnum, crnum, dobth, givnm, midnm, surnm, extnm, gender, post_cd, coun_cd, provc, twnct, brgay, subdv, street, houblk, rmunit, pob_city, pob_prov, pob_cncd, mstat, givnm_fa, midnm_fa, surnm_fa, extnm_fa, givnm_mo, midnm_mo, surnm_mo, extnm_mo, lprif_cd, rprif_cd, lbkuf_cd, rbkuf_cd, height, weight, disftr, tinum, cstat, cc_date, authToken}, Me.insertGSISUmidOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertGSISUmidOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertGSISUmidCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertGSISUmidCompleted(Me, New insertGSISUmidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service/", ResponseNamespace:="http://service/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function isCsnExist(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal csn As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webserviceResponse
            Dim results() As Object = Me.Invoke("isCsnExist", New Object() {authToken, csn})
            Return CType(results(0),webserviceResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub isCsnExistAsync(ByVal authToken As String, ByVal csn As String)
            Me.isCsnExistAsync(authToken, csn, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub isCsnExistAsync(ByVal authToken As String, ByVal csn As String, ByVal userState As Object)
            If (Me.isCsnExistOperationCompleted Is Nothing) Then
                Me.isCsnExistOperationCompleted = AddressOf Me.OnisCsnExistOperationCompleted
            End If
            Me.InvokeAsync("isCsnExist", New Object() {authToken, csn}, Me.isCsnExistOperationCompleted, userState)
        End Sub
        
        Private Sub OnisCsnExistOperationCompleted(ByVal arg As Object)
            If (Not (Me.isCsnExistCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent isCsnExistCompleted(Me, New isCsnExistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service/")>  _
    Partial Public Class webserviceResponse
        
        Private processFlagField As String
        
        Private returnMessageField As String
        
        Private ssnumberField As String
        
        Private umidSSIDTagField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property processFlag() As String
            Get
                Return Me.processFlagField
            End Get
            Set
                Me.processFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property returnMessage() As String
            Get
                Return Me.returnMessageField
            End Get
            Set
                Me.returnMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ssnumber() As String
            Get
                Return Me.ssnumberField
            End Get
            Set
                Me.ssnumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property umidSSIDTag() As String
            Get
                Return Me.umidSSIDTagField
            End Get
            Set
                Me.umidSSIDTagField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub isWithUMIDSSIDCompletedEventHandler(ByVal sender As Object, ByVal e As isWithUMIDSSIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isWithUMIDSSIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webserviceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webserviceResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub isSSSMemberCompletedEventHandler(ByVal sender As Object, ByVal e As isSSSMemberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isSSSMemberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webserviceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webserviceResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub insertGSISUmidCompletedEventHandler(ByVal sender As Object, ByVal e As insertGSISUmidCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertGSISUmidCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webserviceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webserviceResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub isCsnExistCompletedEventHandler(ByVal sender As Object, ByVal e As isCsnExistCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class isCsnExistCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webserviceResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webserviceResponse)
            End Get
        End Property
    End Class
End Namespace
