'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getURL() As String
            Get
                Return CType(Me("getURL"),String)
            End Get
            Set
                Me("getURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property tagPage() As String
            Get
                Return CType(Me("tagPage"),String)
            End Get
            Set
                Me("tagPage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property webPageTag() As String
            Get
                Return CType(Me("webPageTag"),String)
            End Get
            Set
                Me("webPageTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://m01ws079:8888/sss-ssitserve2/")>  _
        Public Property getPermanentURL() As String
            Get
                Return CType(Me("getPermanentURL"),String)
            End Get
            Set
                Me("getPermanentURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property tagInqury() As String
            Get
                Return CType(Me("tagInqury"),String)
            End Get
            Set
                Me("tagInqury") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BenefitTag1() As String
            Get
                Return CType(Me("BenefitTag1"),String)
            End Get
            Set
                Me("BenefitTag1") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=SSIT;uid=sa;pwd=password2013")>  _
        Public ReadOnly Property Setting() As String
            Get
                Return CType(Me("Setting"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property BenefitTag2() As String
            Get
                Return CType(Me("BenefitTag2"),String)
            End Get
            Set
                Me("BenefitTag2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getLogsWeb() As String
            Get
                Return CType(Me("getLogsWeb"),String)
            End Get
            Set
                Me("getLogsWeb") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property autoGenID() As String
            Get
                Return CType(Me("autoGenID"),String)
            End Get
            Set
                Me("autoGenID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lastIDmaternity() As String
            Get
                Return CType(Me("lastIDmaternity"),String)
            End Get
            Set
                Me("lastIDmaternity") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getAdd() As String
            Get
                Return CType(Me("getAdd"),String)
            End Get
            Set
                Me("getAdd") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pageIncremement() As String
            Get
                Return CType(Me("pageIncremement"),String)
            End Get
            Set
                Me("pageIncremement") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://www.sss.gov.ph/sss/login.jsp")>  _
        Public Property sssWebsiteLink() As String
            Get
                Return CType(Me("sssWebsiteLink"),String)
            End Get
            Set
                Me("sssWebsiteLink") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kioskID() As String
            Get
                Return CType(Me("kioskID"),String)
            End Get
            Set
                Me("kioskID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kioskIP() As String
            Get
                Return CType(Me("kioskIP"),String)
            End Get
            Set
                Me("kioskIP") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kioskName() As String
            Get
                Return CType(Me("kioskName"),String)
            End Get
            Set
                Me("kioskName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Server() As String
            Get
                Return CType(Me("db_Server"),String)
            End Get
            Set
                Me("db_Server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_UName() As String
            Get
                Return CType(Me("db_UName"),String)
            End Get
            Set
                Me("db_UName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Pass() As String
            Get
                Return CType(Me("db_Pass"),String)
            End Get
            Set
                Me("db_Pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Name() As String
            Get
                Return CType(Me("db_Name"),String)
            End Get
            Set
                Me("db_Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_DSN() As String
            Get
                Return CType(Me("db_DSN"),String)
            End Get
            Set
                Me("db_DSN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kioskBranch() As String
            Get
                Return CType(Me("kioskBranch"),String)
            End Get
            Set
                Me("kioskBranch") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property lastOnline() As Date
            Get
                Return CType(Me("lastOnline"),Date)
            End Get
            Set
                Me("lastOnline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property lastOffline() As Date
            Get
                Return CType(Me("lastOffline"),Date)
            End Get
            Set
                Me("lastOffline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property firstRun() As String
            Get
                Return CType(Me("firstRun"),String)
            End Get
            Set
                Me("firstRun") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property userType() As Integer
            Get
                Return CType(Me("userType"),Integer)
            End Get
            Set
                Me("userType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property printTag() As Integer
            Get
                Return CType(Me("printTag"),Integer)
            End Get
            Set
                Me("printTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Host() As String
            Get
                Return CType(Me("db_Host"),String)
            End Get
            Set
                Me("db_Host") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Port() As String
            Get
                Return CType(Me("db_Port"),String)
            End Get
            Set
                Me("db_Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_ServiceName() As String
            Get
                Return CType(Me("db_ServiceName"),String)
            End Get
            Set
                Me("db_ServiceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_UserID() As String
            Get
                Return CType(Me("db_UserID"),String)
            End Get
            Set
                Me("db_UserID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property db_Password() As String
            Get
                Return CType(Me("db_Password"),String)
            End Get
            Set
                Me("db_Password") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kiosk_cluster() As String
            Get
                Return CType(Me("kiosk_cluster"),String)
            End Get
            Set
                Me("kiosk_cluster") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property kiosk_group() As String
            Get
                Return CType(Me("kiosk_group"),String)
            End Get
            Set
                Me("kiosk_group") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property authentication() As String
            Get
                Return CType(Me("authentication"),String)
            End Get
            Set
                Me("authentication") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
        Public Property getUmidCardStatus() As Integer
            Get
                Return CType(Me("getUmidCardStatus"),Integer)
            End Get
            Set
                Me("getUmidCardStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property pathLoc() As String
            Get
                Return CType(Me("pathLoc"),String)
            End Get
            Set
                Me("pathLoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property salaryLoanTag() As Integer
            Get
                Return CType(Me("salaryLoanTag"),Integer)
            End Get
            Set
                Me("salaryLoanTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getErNo() As String
            Get
                Return CType(Me("getErNo"),String)
            End Get
            Set
                Me("getErNo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getNameEr() As String
            Get
                Return CType(Me("getNameEr"),String)
            End Get
            Set
                Me("getNameEr") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getEmpStatus() As String
            Get
                Return CType(Me("getEmpStatus"),String)
            End Get
            Set
                Me("getEmpStatus") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ssitsssgov")>  _
        Public Property kioskAdminUser() As String
            Get
                Return CType(Me("kioskAdminUser"),String)
            End Get
            Set
                Me("kioskAdminUser") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("allcardtech@2014!")>  _
        Public Property kioskAdminPass() As String
            Get
                Return CType(Me("kioskAdminPass"),String)
            End Get
            Set
                Me("kioskAdminPass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SSStempFile() As String
            Get
                Return CType(Me("SSStempFile"),String)
            End Get
            Set
                Me("SSStempFile") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property printerPort() As String
            Get
                Return CType(Me("printerPort"),String)
            End Get
            Set
                Me("printerPort") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property errorLoadTag() As Integer
            Get
                Return CType(Me("errorLoadTag"),Integer)
            End Get
            Set
                Me("errorLoadTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dateOfBirth() As String
            Get
                Return CType(Me("dateOfBirth"),String)
            End Get
            Set
                Me("dateOfBirth") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property dateOfCov() As String
            Get
                Return CType(Me("dateOfCov"),String)
            End Get
            Set
                Me("dateOfCov") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lastTransNo() As String
            Get
                Return CType(Me("lastTransNo"),String)
            End Get
            Set
                Me("lastTransNo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://prs:7777/")>  _
        Public Property disclosureURL() As String
            Get
                Return CType(Me("disclosureURL"),String)
            End Get
            Set
                Me("disclosureURL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property errorTag() As String
            Get
                Return CType(Me("errorTag"),String)
            End Get
            Set
                Me("errorTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property transTag() As String
            Get
                Return CType(Me("transTag"),String)
            End Get
            Set
                Me("transTag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property getLumpSum() As String
            Get
                Return CType(Me("getLumpSum"),String)
            End Get
            Set
                Me("getLumpSum") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property UMID() As Integer
            Get
                Return CType(Me("UMID"),Integer)
            End Get
            Set
                Me("UMID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SAM() As Integer
            Get
                Return CType(Me("SAM"),Integer)
            End Get
            Set
                Me("SAM") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OMNIKEY CardMan 5x21-CL 0")>  _
        Public Property SmartCardReader() As String
            Get
                Return CType(Me("SmartCardReader"),String)
            End Get
            Set
                Me("SmartCardReader") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CRN() As String
            Get
                Return CType(Me("CRN"),String)
            End Get
            Set
                Me("CRN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("123456")>  _
        Public Property PIN() As String
            Get
                Return CType(Me("PIN"),String)
            End Get
            Set
                Me("PIN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property SSSCard_SessionTime() As Short
            Get
                Return CType(Me("SSSCard_SessionTime"),Short)
            End Get
            Set
                Me("SSSCard_SessionTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public Property UMIDCard_SessionTime() As Short
            Get
                Return CType(Me("UMIDCard_SessionTime"),Short)
            End Get
            Set
                Me("UMIDCard_SessionTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ncjaluag@allcardtech.com.ph")>  _
        Public Property webFeedEmail() As String
            Get
                Return CType(Me("webFeedEmail"),String)
            End Get
            Set
                Me("webFeedEmail") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CHECK_MEMSTATUS() As String
            Get
                Return CType(Me("CHECK_MEMSTATUS"),String)
            End Get
            Set
                Me("CHECK_MEMSTATUS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property IsCRNJustActivated() As Boolean
            Get
                Return CType(Me("IsCRNJustActivated"),Boolean)
            End Get
            Set
                Me("IsCRNJustActivated") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property lastContribution() As String
            Get
                Return CType(Me("lastContribution"),String)
            End Get
            Set
                Me("lastContribution") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CSN() As String
            Get
                Return CType(Me("CSN"),String)
            End Get
            Set
                Me("CSN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CCDT() As String
            Get
                Return CType(Me("CCDT"),String)
            End Get
            Set
                Me("CCDT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CardPIN() As String
            Get
                Return CType(Me("CardPIN"),String)
            End Get
            Set
                Me("CardPIN") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SS_Number() As String
            Get
                Return CType(Me("SS_Number"),String)
            End Get
            Set
                Me("SS_Number") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property CARD_DATA() As String
            Get
                Return CType(Me("CARD_DATA"),String)
            End Get
            Set
                Me("CARD_DATA") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://sssohs:7777/webcallingds/DisclosureWebserviceImplService")>  _
        Public ReadOnly Property SSIT_SERVER_WS_Disclosure_DisclosureWebserviceImplService() As String
            Get
                Return CType(Me("SSIT_SERVER_WS_Disclosure_DisclosureWebserviceImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.141.249.22:8017/TokenServiceBean/TokenServiceBeanService")>  _
        Public ReadOnly Property SSIT_SERVER_SSSTokenGenerator_TokenDetailsService() As String
            Get
                Return CType(Me("SSIT_SERVER_SSSTokenGenerator_TokenDetailsService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://wws.sss.gov.ph:80/MobileWSBean/MobileWSBeanService")>  _
        Public ReadOnly Property SSIT_SERVER_MobileWS2BeanService_MobileWS2BeanService() As String
            Get
                Return CType(Me("SSIT_SERVER_MobileWS2BeanService_MobileWS2BeanService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ww8.sss.gov.ph:80/eligibwebservice/EligibilityWebserviceImplService")>  _
        Public ReadOnly Property SSIT_SERVER_EligibilityWebserviceImplService_EligibilityWebserviceImplService() As String
            Get
                Return CType(Me("SSIT_SERVER_EligibilityWebserviceImplService_EligibilityWebserviceImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ww8.sss.gov.ph:80/webcallingds/DisclosureWebserviceImplService")>  _
        Public ReadOnly Property SSIT_SERVER_DisclosureWebserviceImplService_DisclosureWebserviceImplService() As String
            Get
                Return CType(Me("SSIT_SERVER_DisclosureWebserviceImplService_DisclosureWebserviceImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.0.161.237:7101/Wes3in1EJBBean/Wes3in1Service")>  _
        Public ReadOnly Property SSIT_SERVER_SimpleWebRegistrationService_SimpleWebRegistrationService() As String
            Get
                Return CType(Me("SSIT_SERVER_SimpleWebRegistrationService_SimpleWebRegistrationService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://m41sv145:7009/testbemws/BankWorkflowWebServiceImplPort")>  _
        Public ReadOnly Property SSIT_SERVER_BankWorkflowWebService_BankWorkflowWebServiceImplService() As String
            Get
                Return CType(Me("SSIT_SERVER_BankWorkflowWebService_BankWorkflowWebServiceImplService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://m41sv145:7009/TestUmidWSBean/UmidService")>  _
        Public ReadOnly Property SSIT_SERVER_UmidService_UmidService() As String
            Get
                Return CType(Me("SSIT_SERVER_UmidService_UmidService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ww8.sss.gov.ph:80/TestOnlineRetirement/OnlineRetirementWebServiceImplServi"& _ 
            "ce")>  _
        Public ReadOnly Property SSIT_SERVER_OnlineRetirementWebServiceImplService_OnlineRetirementWebServiceImplService() As String
            Get
                Return CType(Me("SSIT_SERVER_OnlineRetirementWebServiceImplService_OnlineRetirementWebServiceImplS"& _ 
                    "ervice"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SSIT_SERVER.My.MySettings
            Get
                Return Global.SSIT_SERVER.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
