'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace EligibilityWebserviceImplService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EligibilityWebserviceImplPortBinding", [Namespace]:="http://webservice/")>  _
    Partial Public Class EligibilityWebserviceImplService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private AuthenticateTokenOperationCompleted As System.Threading.SendOrPostCallback
        
        Private calleligibilityOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SSIT_SERVER.My.MySettings.Default.SSIT_SERVER_EligibilityWebserviceImplService_EligibilityWebserviceImplService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event AuthenticateTokenCompleted As AuthenticateTokenCompletedEventHandler
        
        '''<remarks/>
        Public Event calleligibilityCompleted As calleligibilityCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservice/", ResponseNamespace:="http://webservice/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function AuthenticateToken(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal token_id As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> eligibTsReponse
            Dim results() As Object = Me.Invoke("AuthenticateToken", New Object() {token_id})
            Return CType(results(0),eligibTsReponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub AuthenticateTokenAsync(ByVal token_id As String)
            Me.AuthenticateTokenAsync(token_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub AuthenticateTokenAsync(ByVal token_id As String, ByVal userState As Object)
            If (Me.AuthenticateTokenOperationCompleted Is Nothing) Then
                Me.AuthenticateTokenOperationCompleted = AddressOf Me.OnAuthenticateTokenOperationCompleted
            End If
            Me.InvokeAsync("AuthenticateToken", New Object() {token_id}, Me.AuthenticateTokenOperationCompleted, userState)
        End Sub
        
        Private Sub OnAuthenticateTokenOperationCompleted(ByVal arg As Object)
            If (Not (Me.AuthenticateTokenCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent AuthenticateTokenCompleted(Me, New AuthenticateTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://webservice/", ResponseNamespace:="http://webservice/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function calleligibility(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssnum As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal lntyp As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal empid As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal seq_no As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal transac_token As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal token_id As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> eligibWsResponse
            Dim results() As Object = Me.Invoke("calleligibility", New Object() {ssnum, lntyp, empid, seq_no, transac_token, token_id})
            Return CType(results(0),eligibWsResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub calleligibilityAsync(ByVal ssnum As String, ByVal lntyp As String, ByVal empid As String, ByVal seq_no As String, ByVal transac_token As String, ByVal token_id As String)
            Me.calleligibilityAsync(ssnum, lntyp, empid, seq_no, transac_token, token_id, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub calleligibilityAsync(ByVal ssnum As String, ByVal lntyp As String, ByVal empid As String, ByVal seq_no As String, ByVal transac_token As String, ByVal token_id As String, ByVal userState As Object)
            If (Me.calleligibilityOperationCompleted Is Nothing) Then
                Me.calleligibilityOperationCompleted = AddressOf Me.OncalleligibilityOperationCompleted
            End If
            Me.InvokeAsync("calleligibility", New Object() {ssnum, lntyp, empid, seq_no, transac_token, token_id}, Me.calleligibilityOperationCompleted, userState)
        End Sub
        
        Private Sub OncalleligibilityOperationCompleted(ByVal arg As Object)
            If (Not (Me.calleligibilityCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent calleligibilityCompleted(Me, New calleligibilityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice/")>  _
    Partial Public Class eligibTsReponse
        
        Private token_idField As String
        
        Private transac_tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property token_id() As String
            Get
                Return Me.token_idField
            End Get
            Set
                Me.token_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transac_token() As String
            Get
                Return Me.transac_tokenField
            End Get
            Set
                Me.transac_tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice/")>  _
    Partial Public Class rejection
        
        Private delinq_amtField As String
        
        Private haflnamtField As String
        
        Private last12_mscamtField As String
        
        Private last_mscdtField As String
        
        Private last_posted_contriField As String
        
        Private maturity_dtField As String
        
        Private outs_prin_blField As String
        
        Private reasonsField As String
        
        Private total_contri_countField As String
        
        Private twelf_monthField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property delinq_amt() As String
            Get
                Return Me.delinq_amtField
            End Get
            Set
                Me.delinq_amtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property haflnamt() As String
            Get
                Return Me.haflnamtField
            End Get
            Set
                Me.haflnamtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property last12_mscamt() As String
            Get
                Return Me.last12_mscamtField
            End Get
            Set
                Me.last12_mscamtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property last_mscdt() As String
            Get
                Return Me.last_mscdtField
            End Get
            Set
                Me.last_mscdtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property last_posted_contri() As String
            Get
                Return Me.last_posted_contriField
            End Get
            Set
                Me.last_posted_contriField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property maturity_dt() As String
            Get
                Return Me.maturity_dtField
            End Get
            Set
                Me.maturity_dtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property outs_prin_bl() As String
            Get
                Return Me.outs_prin_blField
            End Get
            Set
                Me.outs_prin_blField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property reasons() As String
            Get
                Return Me.reasonsField
            End Get
            Set
                Me.reasonsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property total_contri_count() As String
            Get
                Return Me.total_contri_countField
            End Get
            Set
                Me.total_contri_countField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property twelf_month() As String
            Get
                Return Me.twelf_monthField
            End Get
            Set
                Me.twelf_monthField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice/")>  _
    Partial Public Class qual
        
        Private adv_interField As String
        
        Private adv_interestField As String
        
        Private ave_mscField As String
        
        Private due_dateField As String
        
        Private first_amort_dateField As String
        
        Private ln_amountField As String
        
        Private ln_monthField As String
        
        Private monthly_amortField As String
        
        Private net_lnamtField As String
        
        Private pr_lndedField As String
        
        Private serv_feeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property adv_inter() As String
            Get
                Return Me.adv_interField
            End Get
            Set
                Me.adv_interField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property adv_interest() As String
            Get
                Return Me.adv_interestField
            End Get
            Set
                Me.adv_interestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ave_msc() As String
            Get
                Return Me.ave_mscField
            End Get
            Set
                Me.ave_mscField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property due_date() As String
            Get
                Return Me.due_dateField
            End Get
            Set
                Me.due_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property first_amort_date() As String
            Get
                Return Me.first_amort_dateField
            End Get
            Set
                Me.first_amort_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ln_amount() As String
            Get
                Return Me.ln_amountField
            End Get
            Set
                Me.ln_amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ln_month() As String
            Get
                Return Me.ln_monthField
            End Get
            Set
                Me.ln_monthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property monthly_amort() As String
            Get
                Return Me.monthly_amortField
            End Get
            Set
                Me.monthly_amortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property net_lnamt() As String
            Get
                Return Me.net_lnamtField
            End Get
            Set
                Me.net_lnamtField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property pr_lnded() As String
            Get
                Return Me.pr_lndedField
            End Get
            Set
                Me.pr_lndedField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serv_fee() As String
            Get
                Return Me.serv_feeField
            End Get
            Set
                Me.serv_feeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice/")>  _
    Partial Public Class loan
        
        Private first_amortizationField As String
        
        Private loan_amountField As String
        
        Private loan_dateField As String
        
        Private loan_tagField As String
        
        Private loan_typeField As String
        
        Private outstanding_balField As String
        
        Private stmt_dateField As String
        
        Private total_obligationField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property first_amortization() As String
            Get
                Return Me.first_amortizationField
            End Get
            Set
                Me.first_amortizationField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loan_amount() As String
            Get
                Return Me.loan_amountField
            End Get
            Set
                Me.loan_amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loan_date() As String
            Get
                Return Me.loan_dateField
            End Get
            Set
                Me.loan_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loan_tag() As String
            Get
                Return Me.loan_tagField
            End Get
            Set
                Me.loan_tagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loan_type() As String
            Get
                Return Me.loan_typeField
            End Get
            Set
                Me.loan_typeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property outstanding_bal() As String
            Get
                Return Me.outstanding_balField
            End Get
            Set
                Me.outstanding_balField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property stmt_date() As String
            Get
                Return Me.stmt_dateField
            End Get
            Set
                Me.stmt_dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property total_obligation() As String
            Get
                Return Me.total_obligationField
            End Get
            Set
                Me.total_obligationField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://webservice/")>  _
    Partial Public Class eligibWsResponse
        
        Private appl_stField As String
        
        Private empidField As String
        
        Private lntypField As String
        
        Private loan_balanceField() As loan
        
        Private loan_monthField As String
        
        Private loanableAmountField As String
        
        Private maxLoanableAmountField As String
        
        Private monthly_amortField As String
        
        Private msgField As String
        
        Private netloanField As String
        
        Private qual_info_curField() As qual
        
        Private rej_dtlsField() As rejection
        
        Private rejlistField As String
        
        Private sadateField As String
        
        Private seq_noField As String
        
        Private serviceFeeField As String
        
        Private ssnumField As String
        
        Private token_idField As String
        
        Private totalbalanceField As String
        
        Private transac_tokenField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property appl_st() As String
            Get
                Return Me.appl_stField
            End Get
            Set
                Me.appl_stField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property empid() As String
            Get
                Return Me.empidField
            End Get
            Set
                Me.empidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lntyp() As String
            Get
                Return Me.lntypField
            End Get
            Set
                Me.lntypField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("loan_balance", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property loan_balance() As loan()
            Get
                Return Me.loan_balanceField
            End Get
            Set
                Me.loan_balanceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loan_month() As String
            Get
                Return Me.loan_monthField
            End Get
            Set
                Me.loan_monthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property loanableAmount() As String
            Get
                Return Me.loanableAmountField
            End Get
            Set
                Me.loanableAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property maxLoanableAmount() As String
            Get
                Return Me.maxLoanableAmountField
            End Get
            Set
                Me.maxLoanableAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property monthly_amort() As String
            Get
                Return Me.monthly_amortField
            End Get
            Set
                Me.monthly_amortField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property msg() As String
            Get
                Return Me.msgField
            End Get
            Set
                Me.msgField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property netloan() As String
            Get
                Return Me.netloanField
            End Get
            Set
                Me.netloanField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("qual_info_cur", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property qual_info_cur() As qual()
            Get
                Return Me.qual_info_curField
            End Get
            Set
                Me.qual_info_curField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("rej_dtls", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=true)>  _
        Public Property rej_dtls() As rejection()
            Get
                Return Me.rej_dtlsField
            End Get
            Set
                Me.rej_dtlsField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property rejlist() As String
            Get
                Return Me.rejlistField
            End Get
            Set
                Me.rejlistField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property sadate() As String
            Get
                Return Me.sadateField
            End Get
            Set
                Me.sadateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property seq_no() As String
            Get
                Return Me.seq_noField
            End Get
            Set
                Me.seq_noField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property serviceFee() As String
            Get
                Return Me.serviceFeeField
            End Get
            Set
                Me.serviceFeeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ssnum() As String
            Get
                Return Me.ssnumField
            End Get
            Set
                Me.ssnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property token_id() As String
            Get
                Return Me.token_idField
            End Get
            Set
                Me.token_idField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property totalbalance() As String
            Get
                Return Me.totalbalanceField
            End Get
            Set
                Me.totalbalanceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transac_token() As String
            Get
                Return Me.transac_tokenField
            End Get
            Set
                Me.transac_tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub AuthenticateTokenCompletedEventHandler(ByVal sender As Object, ByVal e As AuthenticateTokenCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class AuthenticateTokenCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As eligibTsReponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),eligibTsReponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub calleligibilityCompletedEventHandler(ByVal sender As Object, ByVal e As calleligibilityCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class calleligibilityCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As eligibWsResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),eligibWsResponse)
            End Get
        End Property
    End Class
End Namespace
