'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace SimpleWebRegistrationService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Wes3in1ServicePortBinding", [Namespace]:="http://service.sss/")>  _
    Partial Public Class Wes3in1Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private validateUserIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private validateEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertToWesRegistrationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getMemberRecordOperationCompleted As System.Threading.SendOrPostCallback
        
        Private setMemberToPermanentOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SSIT_SERVER.My.MySettings.Default.SSIT_SERVER_SimpleWebRegistrationService_SimpleWebRegistrationService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event validateUserIdCompleted As validateUserIdCompletedEventHandler
        
        '''<remarks/>
        Public Event validateEmailCompleted As validateEmailCompletedEventHandler
        
        '''<remarks/>
        Public Event insertToWesRegistrationCompleted As insertToWesRegistrationCompletedEventHandler
        
        '''<remarks/>
        Public Event getMemberRecordCompleted As getMemberRecordCompletedEventHandler
        
        '''<remarks/>
        Public Event setMemberToPermanentCompleted As setMemberToPermanentCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.sss/", ResponseNamespace:="http://service.sss/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function validateUserId(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssNumber As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal userid As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webResponse
            Dim results() As Object = Me.Invoke("validateUserId", New Object() {authToken, ssNumber, userid})
            Return CType(results(0),webResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validateUserIdAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal userid As String)
            Me.validateUserIdAsync(authToken, ssNumber, userid, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validateUserIdAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal userid As String, ByVal userState As Object)
            If (Me.validateUserIdOperationCompleted Is Nothing) Then
                Me.validateUserIdOperationCompleted = AddressOf Me.OnvalidateUserIdOperationCompleted
            End If
            Me.InvokeAsync("validateUserId", New Object() {authToken, ssNumber, userid}, Me.validateUserIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidateUserIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.validateUserIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validateUserIdCompleted(Me, New validateUserIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.sss/", ResponseNamespace:="http://service.sss/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function validateEmail(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssNumber As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal email As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webResponse
            Dim results() As Object = Me.Invoke("validateEmail", New Object() {authToken, ssNumber, email})
            Return CType(results(0),webResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validateEmailAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal email As String)
            Me.validateEmailAsync(authToken, ssNumber, email, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validateEmailAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal email As String, ByVal userState As Object)
            If (Me.validateEmailOperationCompleted Is Nothing) Then
                Me.validateEmailOperationCompleted = AddressOf Me.OnvalidateEmailOperationCompleted
            End If
            Me.InvokeAsync("validateEmail", New Object() {authToken, ssNumber, email}, Me.validateEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidateEmailOperationCompleted(ByVal arg As Object)
            If (Not (Me.validateEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validateEmailCompleted(Me, New validateEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.sss/", ResponseNamespace:="http://service.sss/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertToWesRegistration(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssNumber As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal userId As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webResponse
            Dim results() As Object = Me.Invoke("insertToWesRegistration", New Object() {authToken, ssNumber, userId})
            Return CType(results(0),webResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertToWesRegistrationAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal userId As String)
            Me.insertToWesRegistrationAsync(authToken, ssNumber, userId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertToWesRegistrationAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal userId As String, ByVal userState As Object)
            If (Me.insertToWesRegistrationOperationCompleted Is Nothing) Then
                Me.insertToWesRegistrationOperationCompleted = AddressOf Me.OninsertToWesRegistrationOperationCompleted
            End If
            Me.InvokeAsync("insertToWesRegistration", New Object() {authToken, ssNumber, userId}, Me.insertToWesRegistrationOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertToWesRegistrationOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertToWesRegistrationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertToWesRegistrationCompleted(Me, New insertToWesRegistrationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.sss/", ResponseNamespace:="http://service.sss/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getMemberRecord(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal arg1 As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal transactionNo As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> memberRecord
            Dim results() As Object = Me.Invoke("getMemberRecord", New Object() {authToken, arg1, transactionNo})
            Return CType(results(0),memberRecord)
        End Function
        
        '''<remarks/>
        Public Overloads Sub getMemberRecordAsync(ByVal authToken As String, ByVal arg1 As String, ByVal transactionNo As String)
            Me.getMemberRecordAsync(authToken, arg1, transactionNo, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getMemberRecordAsync(ByVal authToken As String, ByVal arg1 As String, ByVal transactionNo As String, ByVal userState As Object)
            If (Me.getMemberRecordOperationCompleted Is Nothing) Then
                Me.getMemberRecordOperationCompleted = AddressOf Me.OngetMemberRecordOperationCompleted
            End If
            Me.InvokeAsync("getMemberRecord", New Object() {authToken, arg1, transactionNo}, Me.getMemberRecordOperationCompleted, userState)
        End Sub
        
        Private Sub OngetMemberRecordOperationCompleted(ByVal arg As Object)
            If (Not (Me.getMemberRecordCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getMemberRecordCompleted(Me, New getMemberRecordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.sss/", ResponseNamespace:="http://service.sss/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function setMemberToPermanent(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal authToken As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ssNumber As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> webResponse
            Dim results() As Object = Me.Invoke("setMemberToPermanent", New Object() {authToken, ssNumber})
            Return CType(results(0),webResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub setMemberToPermanentAsync(ByVal authToken As String, ByVal ssNumber As String)
            Me.setMemberToPermanentAsync(authToken, ssNumber, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub setMemberToPermanentAsync(ByVal authToken As String, ByVal ssNumber As String, ByVal userState As Object)
            If (Me.setMemberToPermanentOperationCompleted Is Nothing) Then
                Me.setMemberToPermanentOperationCompleted = AddressOf Me.OnsetMemberToPermanentOperationCompleted
            End If
            Me.InvokeAsync("setMemberToPermanent", New Object() {authToken, ssNumber}, Me.setMemberToPermanentOperationCompleted, userState)
        End Sub
        
        Private Sub OnsetMemberToPermanentOperationCompleted(ByVal arg As Object)
            If (Not (Me.setMemberToPermanentCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent setMemberToPermanentCompleted(Me, New setMemberToPermanentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.sss/")>  _
    Partial Public Class webResponse
        
        Private emailField As String
        
        Private processFlagField As String
        
        Private returnMessageField As String
        
        Private ssNumberField As String
        
        Private userIdField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property processFlag() As String
            Get
                Return Me.processFlagField
            End Get
            Set
                Me.processFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property returnMessage() As String
            Get
                Return Me.returnMessageField
            End Get
            Set
                Me.returnMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ssNumber() As String
            Get
                Return Me.ssNumberField
            End Get
            Set
                Me.ssNumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property userId() As String
            Get
                Return Me.userIdField
            End Get
            Set
                Me.userIdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.sss/")>  _
    Partial Public Class memberRecord
        
        Private bankCodeField As String
        
        Private barangay_nameField As String
        
        Private birthPlaceCityField As String
        
        Private birthPlaceCountryField As String
        
        Private birthPlaceProvField As String
        
        Private brstnField As String
        
        Private city_municipilityField As String
        
        Private civilStatusField As String
        
        Private country_nameField As String
        
        Private dateOfBirthField As String
        
        Private emailField As String
        
        Private enrolmentTypeField As String
        
        Private errorMessageField As String
        
        Private extensionNameField As String
        
        Private firstNameField As String
        
        Private firstName_faField As String
        
        Private firstName_moField As String
        
        Private genderField As String
        
        Private heightField As String
        
        Private house_blk_noField As String
        
        Private lastNameField As String
        
        Private lastName_faField As String
        
        Private lastName_moField As String
        
        Private middleNameField As String
        
        Private middleName_faField As String
        
        Private middleName_moField As String
        
        Private mobileNoField As String
        
        Private postal_codeField As String
        
        Private processFlagField As String
        
        Private province_nameField As String
        
        Private replacementCodeField As String
        
        Private ssnumField As String
        
        Private streetField As String
        
        Private subdivisionField As String
        
        Private telNoField As String
        
        Private unit_bldg_nameField As String
        
        Private weightField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property bankCode() As String
            Get
                Return Me.bankCodeField
            End Get
            Set
                Me.bankCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property barangay_name() As String
            Get
                Return Me.barangay_nameField
            End Get
            Set
                Me.barangay_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property birthPlaceCity() As String
            Get
                Return Me.birthPlaceCityField
            End Get
            Set
                Me.birthPlaceCityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property birthPlaceCountry() As String
            Get
                Return Me.birthPlaceCountryField
            End Get
            Set
                Me.birthPlaceCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property birthPlaceProv() As String
            Get
                Return Me.birthPlaceProvField
            End Get
            Set
                Me.birthPlaceProvField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property brstn() As String
            Get
                Return Me.brstnField
            End Get
            Set
                Me.brstnField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property city_municipility() As String
            Get
                Return Me.city_municipilityField
            End Get
            Set
                Me.city_municipilityField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property civilStatus() As String
            Get
                Return Me.civilStatusField
            End Get
            Set
                Me.civilStatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property country_name() As String
            Get
                Return Me.country_nameField
            End Get
            Set
                Me.country_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property dateOfBirth() As String
            Get
                Return Me.dateOfBirthField
            End Get
            Set
                Me.dateOfBirthField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property email() As String
            Get
                Return Me.emailField
            End Get
            Set
                Me.emailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property enrolmentType() As String
            Get
                Return Me.enrolmentTypeField
            End Get
            Set
                Me.enrolmentTypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property errorMessage() As String
            Get
                Return Me.errorMessageField
            End Get
            Set
                Me.errorMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property extensionName() As String
            Get
                Return Me.extensionNameField
            End Get
            Set
                Me.extensionNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property firstName() As String
            Get
                Return Me.firstNameField
            End Get
            Set
                Me.firstNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property firstName_fa() As String
            Get
                Return Me.firstName_faField
            End Get
            Set
                Me.firstName_faField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property firstName_mo() As String
            Get
                Return Me.firstName_moField
            End Get
            Set
                Me.firstName_moField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property gender() As String
            Get
                Return Me.genderField
            End Get
            Set
                Me.genderField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property height() As String
            Get
                Return Me.heightField
            End Get
            Set
                Me.heightField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property house_blk_no() As String
            Get
                Return Me.house_blk_noField
            End Get
            Set
                Me.house_blk_noField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastName() As String
            Get
                Return Me.lastNameField
            End Get
            Set
                Me.lastNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastName_fa() As String
            Get
                Return Me.lastName_faField
            End Get
            Set
                Me.lastName_faField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property lastName_mo() As String
            Get
                Return Me.lastName_moField
            End Get
            Set
                Me.lastName_moField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property middleName() As String
            Get
                Return Me.middleNameField
            End Get
            Set
                Me.middleNameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property middleName_fa() As String
            Get
                Return Me.middleName_faField
            End Get
            Set
                Me.middleName_faField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property middleName_mo() As String
            Get
                Return Me.middleName_moField
            End Get
            Set
                Me.middleName_moField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mobileNo() As String
            Get
                Return Me.mobileNoField
            End Get
            Set
                Me.mobileNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property postal_code() As String
            Get
                Return Me.postal_codeField
            End Get
            Set
                Me.postal_codeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property processFlag() As String
            Get
                Return Me.processFlagField
            End Get
            Set
                Me.processFlagField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property province_name() As String
            Get
                Return Me.province_nameField
            End Get
            Set
                Me.province_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property replacementCode() As String
            Get
                Return Me.replacementCodeField
            End Get
            Set
                Me.replacementCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ssnum() As String
            Get
                Return Me.ssnumField
            End Get
            Set
                Me.ssnumField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property street() As String
            Get
                Return Me.streetField
            End Get
            Set
                Me.streetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property subdivision() As String
            Get
                Return Me.subdivisionField
            End Get
            Set
                Me.subdivisionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property telNo() As String
            Get
                Return Me.telNoField
            End Get
            Set
                Me.telNoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property unit_bldg_name() As String
            Get
                Return Me.unit_bldg_nameField
            End Get
            Set
                Me.unit_bldg_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property weight() As String
            Get
                Return Me.weightField
            End Get
            Set
                Me.weightField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub validateUserIdCompletedEventHandler(ByVal sender As Object, ByVal e As validateUserIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validateUserIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub validateEmailCompletedEventHandler(ByVal sender As Object, ByVal e As validateEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validateEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub insertToWesRegistrationCompletedEventHandler(ByVal sender As Object, ByVal e As insertToWesRegistrationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertToWesRegistrationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webResponse)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getMemberRecordCompletedEventHandler(ByVal sender As Object, ByVal e As getMemberRecordCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getMemberRecordCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As memberRecord
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),memberRecord)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub setMemberToPermanentCompletedEventHandler(ByVal sender As Object, ByVal e As setMemberToPermanentCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class setMemberToPermanentCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As webResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),webResponse)
            End Get
        End Property
    End Class
End Namespace
