'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace BankWorkflowWebService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BankWorkflowWebServiceImplPortBinding", [Namespace]:="http://bem/")>  _
    Partial Public Class BankWorkflowWebServiceImplService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private getAccountTypeListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getMainBankListOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getBankAccountListBySSNumberOperationCompleted As System.Threading.SendOrPostCallback
        
        Private insertAccountInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private deactivateAccInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private getBankAccountListByACOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SSIT_SERVER.My.MySettings.Default.SSIT_SERVER_BankWorkflowWebService_BankWorkflowWebServiceImplService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event getAccountTypeListCompleted As getAccountTypeListCompletedEventHandler
        
        '''<remarks/>
        Public Event getMainBankListCompleted As getMainBankListCompletedEventHandler
        
        '''<remarks/>
        Public Event getBankAccountListBySSNumberCompleted As getBankAccountListBySSNumberCompletedEventHandler
        
        '''<remarks/>
        Public Event insertAccountInfoCompleted As insertAccountInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event deactivateAccInfoCompleted As deactivateAccInfoCompletedEventHandler
        
        '''<remarks/>
        Public Event getBankAccountListByACCompleted As getBankAccountListByACCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getAccountTypeList(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> accountTypeWorkflow()
            Dim results() As Object = Me.Invoke("getAccountTypeList", New Object() {TokenId})
            Return CType(results(0),accountTypeWorkflow())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getAccountTypeListAsync(ByVal TokenId As String)
            Me.getAccountTypeListAsync(TokenId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getAccountTypeListAsync(ByVal TokenId As String, ByVal userState As Object)
            If (Me.getAccountTypeListOperationCompleted Is Nothing) Then
                Me.getAccountTypeListOperationCompleted = AddressOf Me.OngetAccountTypeListOperationCompleted
            End If
            Me.InvokeAsync("getAccountTypeList", New Object() {TokenId}, Me.getAccountTypeListOperationCompleted, userState)
        End Sub
        
        Private Sub OngetAccountTypeListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getAccountTypeListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getAccountTypeListCompleted(Me, New getAccountTypeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getMainBankList(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> bankWorkflow()
            Dim results() As Object = Me.Invoke("getMainBankList", New Object() {TokenId})
            Return CType(results(0),bankWorkflow())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getMainBankListAsync(ByVal TokenId As String)
            Me.getMainBankListAsync(TokenId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getMainBankListAsync(ByVal TokenId As String, ByVal userState As Object)
            If (Me.getMainBankListOperationCompleted Is Nothing) Then
                Me.getMainBankListOperationCompleted = AddressOf Me.OngetMainBankListOperationCompleted
            End If
            Me.InvokeAsync("getMainBankList", New Object() {TokenId}, Me.getMainBankListOperationCompleted, userState)
        End Sub
        
        Private Sub OngetMainBankListOperationCompleted(ByVal arg As Object)
            If (Not (Me.getMainBankListCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getMainBankListCompleted(Me, New getMainBankListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getBankAccountListBySSNumber(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal SS_NUMBER As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> accountNumberWorkflow()
            Dim results() As Object = Me.Invoke("getBankAccountListBySSNumber", New Object() {TokenId, SS_NUMBER})
            Return CType(results(0),accountNumberWorkflow())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getBankAccountListBySSNumberAsync(ByVal TokenId As String, ByVal SS_NUMBER As String)
            Me.getBankAccountListBySSNumberAsync(TokenId, SS_NUMBER, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getBankAccountListBySSNumberAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal userState As Object)
            If (Me.getBankAccountListBySSNumberOperationCompleted Is Nothing) Then
                Me.getBankAccountListBySSNumberOperationCompleted = AddressOf Me.OngetBankAccountListBySSNumberOperationCompleted
            End If
            Me.InvokeAsync("getBankAccountListBySSNumber", New Object() {TokenId, SS_NUMBER}, Me.getBankAccountListBySSNumberOperationCompleted, userState)
        End Sub
        
        Private Sub OngetBankAccountListBySSNumberOperationCompleted(ByVal arg As Object)
            If (Not (Me.getBankAccountListBySSNumberCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getBankAccountListBySSNumberCompleted(Me, New getBankAccountListBySSNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function insertAccountInfo(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal SS_NUMBER As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal MEMBER_TYPE As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal NEW_BANK_CODE As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal NEW_BRSTN As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal NEW_ACCNT_NUMBER As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal ACCNT_TYPE As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal E_CHANNEL As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal WES_ACCNT As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> insertAccntInfoWorkflow
            Dim results() As Object = Me.Invoke("insertAccountInfo", New Object() {TokenId, SS_NUMBER, MEMBER_TYPE, NEW_BANK_CODE, NEW_BRSTN, NEW_ACCNT_NUMBER, ACCNT_TYPE, E_CHANNEL, WES_ACCNT})
            Return CType(results(0),insertAccntInfoWorkflow)
        End Function
        
        '''<remarks/>
        Public Overloads Sub insertAccountInfoAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal MEMBER_TYPE As String, ByVal NEW_BANK_CODE As String, ByVal NEW_BRSTN As String, ByVal NEW_ACCNT_NUMBER As String, ByVal ACCNT_TYPE As String, ByVal E_CHANNEL As String, ByVal WES_ACCNT As String)
            Me.insertAccountInfoAsync(TokenId, SS_NUMBER, MEMBER_TYPE, NEW_BANK_CODE, NEW_BRSTN, NEW_ACCNT_NUMBER, ACCNT_TYPE, E_CHANNEL, WES_ACCNT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub insertAccountInfoAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal MEMBER_TYPE As String, ByVal NEW_BANK_CODE As String, ByVal NEW_BRSTN As String, ByVal NEW_ACCNT_NUMBER As String, ByVal ACCNT_TYPE As String, ByVal E_CHANNEL As String, ByVal WES_ACCNT As String, ByVal userState As Object)
            If (Me.insertAccountInfoOperationCompleted Is Nothing) Then
                Me.insertAccountInfoOperationCompleted = AddressOf Me.OninsertAccountInfoOperationCompleted
            End If
            Me.InvokeAsync("insertAccountInfo", New Object() {TokenId, SS_NUMBER, MEMBER_TYPE, NEW_BANK_CODE, NEW_BRSTN, NEW_ACCNT_NUMBER, ACCNT_TYPE, E_CHANNEL, WES_ACCNT}, Me.insertAccountInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OninsertAccountInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.insertAccountInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent insertAccountInfoCompleted(Me, New insertAccountInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function deactivateAccInfo(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal SS_NUMBER As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal BankCode As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal BankAccNo As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal WES_ACCNT As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> accountDeactiveWorkflow()
            Dim results() As Object = Me.Invoke("deactivateAccInfo", New Object() {TokenId, SS_NUMBER, BankCode, BankAccNo, WES_ACCNT})
            Return CType(results(0),accountDeactiveWorkflow())
        End Function
        
        '''<remarks/>
        Public Overloads Sub deactivateAccInfoAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal BankCode As String, ByVal BankAccNo As String, ByVal WES_ACCNT As String)
            Me.deactivateAccInfoAsync(TokenId, SS_NUMBER, BankCode, BankAccNo, WES_ACCNT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub deactivateAccInfoAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal BankCode As String, ByVal BankAccNo As String, ByVal WES_ACCNT As String, ByVal userState As Object)
            If (Me.deactivateAccInfoOperationCompleted Is Nothing) Then
                Me.deactivateAccInfoOperationCompleted = AddressOf Me.OndeactivateAccInfoOperationCompleted
            End If
            Me.InvokeAsync("deactivateAccInfo", New Object() {TokenId, SS_NUMBER, BankCode, BankAccNo, WES_ACCNT}, Me.deactivateAccInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OndeactivateAccInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.deactivateAccInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent deactivateAccInfoCompleted(Me, New deactivateAccInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://bem/", ResponseNamespace:="http://bem/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function getBankAccountListByAC(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal TokenId As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal SS_NUMBER As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal APP_SYS_CODE As String) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> accountNumberWorkflow()
            Dim results() As Object = Me.Invoke("getBankAccountListByAC", New Object() {TokenId, SS_NUMBER, APP_SYS_CODE})
            Return CType(results(0),accountNumberWorkflow())
        End Function
        
        '''<remarks/>
        Public Overloads Sub getBankAccountListByACAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal APP_SYS_CODE As String)
            Me.getBankAccountListByACAsync(TokenId, SS_NUMBER, APP_SYS_CODE, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub getBankAccountListByACAsync(ByVal TokenId As String, ByVal SS_NUMBER As String, ByVal APP_SYS_CODE As String, ByVal userState As Object)
            If (Me.getBankAccountListByACOperationCompleted Is Nothing) Then
                Me.getBankAccountListByACOperationCompleted = AddressOf Me.OngetBankAccountListByACOperationCompleted
            End If
            Me.InvokeAsync("getBankAccountListByAC", New Object() {TokenId, SS_NUMBER, APP_SYS_CODE}, Me.getBankAccountListByACOperationCompleted, userState)
        End Sub
        
        Private Sub OngetBankAccountListByACOperationCompleted(ByVal arg As Object)
            If (Not (Me.getBankAccountListByACCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent getBankAccountListByACCompleted(Me, New getBankAccountListByACCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bem/")>  _
    Partial Public Class accountTypeWorkflow
        
        Private aCT_DESCField As String
        
        Private aCT_TYPEField As String
        
        Private rEPLY_CODEField As Integer
        
        Private rEPLY_MESSAGEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACT_DESC() As String
            Get
                Return Me.aCT_DESCField
            End Get
            Set
                Me.aCT_DESCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACT_TYPE() As String
            Get
                Return Me.aCT_TYPEField
            End Get
            Set
                Me.aCT_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_CODE() As Integer
            Get
                Return Me.rEPLY_CODEField
            End Get
            Set
                Me.rEPLY_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_MESSAGE() As String
            Get
                Return Me.rEPLY_MESSAGEField
            End Get
            Set
                Me.rEPLY_MESSAGEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bem/")>  _
    Partial Public Class accountDeactiveWorkflow
        
        Private bANK_ACCNOField As String
        
        Private bANK_CODEField As String
        
        Private bANK_NAMEField As String
        
        Private rEPLY_CODEField As Integer
        
        Private rEPLY_MESSAGEField As String
        
        Private sS_NUMBERField As String
        
        Private wES_ACCNTField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_ACCNO() As String
            Get
                Return Me.bANK_ACCNOField
            End Get
            Set
                Me.bANK_ACCNOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_CODE() As String
            Get
                Return Me.bANK_CODEField
            End Get
            Set
                Me.bANK_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_NAME() As String
            Get
                Return Me.bANK_NAMEField
            End Get
            Set
                Me.bANK_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_CODE() As Integer
            Get
                Return Me.rEPLY_CODEField
            End Get
            Set
                Me.rEPLY_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_MESSAGE() As String
            Get
                Return Me.rEPLY_MESSAGEField
            End Get
            Set
                Me.rEPLY_MESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SS_NUMBER() As String
            Get
                Return Me.sS_NUMBERField
            End Get
            Set
                Me.sS_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WES_ACCNT() As String
            Get
                Return Me.wES_ACCNTField
            End Get
            Set
                Me.wES_ACCNTField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bem/")>  _
    Partial Public Class insertAccntInfoWorkflow
        
        Private aCCNT_TYPEField As String
        
        Private bNK_ACCT_IDField As String
        
        Private e_CHANNELField As String
        
        Private mEMBER_TYPEField As String
        
        Private nEW_ACCNT_NUMBERField As String
        
        Private nEW_BANK_CODEField As String
        
        Private nEW_BRSTNField As String
        
        Private oLD_ACCNT_NUMBERField As String
        
        Private oLD_BANK_CODEField As String
        
        Private rEPLY_CODEField As Integer
        
        Private rEPLY_MESSAGEField As String
        
        Private sS_NUMBERField As String
        
        Private tRANS_TYPEField As String
        
        Private wES_ACCNTField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACCNT_TYPE() As String
            Get
                Return Me.aCCNT_TYPEField
            End Get
            Set
                Me.aCCNT_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BNK_ACCT_ID() As String
            Get
                Return Me.bNK_ACCT_IDField
            End Get
            Set
                Me.bNK_ACCT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property e_CHANNEL() As String
            Get
                Return Me.e_CHANNELField
            End Get
            Set
                Me.e_CHANNELField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MEMBER_TYPE() As String
            Get
                Return Me.mEMBER_TYPEField
            End Get
            Set
                Me.mEMBER_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NEW_ACCNT_NUMBER() As String
            Get
                Return Me.nEW_ACCNT_NUMBERField
            End Get
            Set
                Me.nEW_ACCNT_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NEW_BANK_CODE() As String
            Get
                Return Me.nEW_BANK_CODEField
            End Get
            Set
                Me.nEW_BANK_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NEW_BRSTN() As String
            Get
                Return Me.nEW_BRSTNField
            End Get
            Set
                Me.nEW_BRSTNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OLD_ACCNT_NUMBER() As String
            Get
                Return Me.oLD_ACCNT_NUMBERField
            End Get
            Set
                Me.oLD_ACCNT_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OLD_BANK_CODE() As String
            Get
                Return Me.oLD_BANK_CODEField
            End Get
            Set
                Me.oLD_BANK_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_CODE() As Integer
            Get
                Return Me.rEPLY_CODEField
            End Get
            Set
                Me.rEPLY_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_MESSAGE() As String
            Get
                Return Me.rEPLY_MESSAGEField
            End Get
            Set
                Me.rEPLY_MESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SS_NUMBER() As String
            Get
                Return Me.sS_NUMBERField
            End Get
            Set
                Me.sS_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TRANS_TYPE() As String
            Get
                Return Me.tRANS_TYPEField
            End Get
            Set
                Me.tRANS_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property WES_ACCNT() As String
            Get
                Return Me.wES_ACCNTField
            End Get
            Set
                Me.wES_ACCNTField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bem/")>  _
    Partial Public Class accountNumberWorkflow
        
        Private aCCNT_NUMBERField As String
        
        Private aCCNT_TYPEField As String
        
        Private aPP_SYS_CODEField As String
        
        Private bANK_CODEField As String
        
        Private bANK_DEPBNKField As String
        
        Private bANK_NAMEField As String
        
        Private bB_NAMEField As String
        
        Private bNK_ACCT_IDField As String
        
        Private bRSTNField As String
        
        Private dISB_TYPE_CODEField As String
        
        Private dISB_TYPE_DESCField As String
        
        Private rEPLY_CODEField As Integer
        
        Private rEPLY_MESSAGEField As String
        
        Private sS_NUMBERField As String
        
        Private sTATUSField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACCNT_NUMBER() As String
            Get
                Return Me.aCCNT_NUMBERField
            End Get
            Set
                Me.aCCNT_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ACCNT_TYPE() As String
            Get
                Return Me.aCCNT_TYPEField
            End Get
            Set
                Me.aCCNT_TYPEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property APP_SYS_CODE() As String
            Get
                Return Me.aPP_SYS_CODEField
            End Get
            Set
                Me.aPP_SYS_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_CODE() As String
            Get
                Return Me.bANK_CODEField
            End Get
            Set
                Me.bANK_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_DEPBNK() As String
            Get
                Return Me.bANK_DEPBNKField
            End Get
            Set
                Me.bANK_DEPBNKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_NAME() As String
            Get
                Return Me.bANK_NAMEField
            End Get
            Set
                Me.bANK_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BB_NAME() As String
            Get
                Return Me.bB_NAMEField
            End Get
            Set
                Me.bB_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BNK_ACCT_ID() As String
            Get
                Return Me.bNK_ACCT_IDField
            End Get
            Set
                Me.bNK_ACCT_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BRSTN() As String
            Get
                Return Me.bRSTNField
            End Get
            Set
                Me.bRSTNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DISB_TYPE_CODE() As String
            Get
                Return Me.dISB_TYPE_CODEField
            End Get
            Set
                Me.dISB_TYPE_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DISB_TYPE_DESC() As String
            Get
                Return Me.dISB_TYPE_DESCField
            End Get
            Set
                Me.dISB_TYPE_DESCField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_CODE() As Integer
            Get
                Return Me.rEPLY_CODEField
            End Get
            Set
                Me.rEPLY_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_MESSAGE() As String
            Get
                Return Me.rEPLY_MESSAGEField
            End Get
            Set
                Me.rEPLY_MESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SS_NUMBER() As String
            Get
                Return Me.sS_NUMBERField
            End Get
            Set
                Me.sS_NUMBERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://bem/")>  _
    Partial Public Class bankWorkflow
        
        Private bANK_BRSTNField As String
        
        Private bANK_CODEField As String
        
        Private bANK_DEPBNKField As String
        
        Private bANK_NAMEField As String
        
        Private rEPLY_CODEField As Integer
        
        Private rEPLY_MESSAGEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_BRSTN() As String
            Get
                Return Me.bANK_BRSTNField
            End Get
            Set
                Me.bANK_BRSTNField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_CODE() As String
            Get
                Return Me.bANK_CODEField
            End Get
            Set
                Me.bANK_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_DEPBNK() As String
            Get
                Return Me.bANK_DEPBNKField
            End Get
            Set
                Me.bANK_DEPBNKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BANK_NAME() As String
            Get
                Return Me.bANK_NAMEField
            End Get
            Set
                Me.bANK_NAMEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_CODE() As Integer
            Get
                Return Me.rEPLY_CODEField
            End Get
            Set
                Me.rEPLY_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property REPLY_MESSAGE() As String
            Get
                Return Me.rEPLY_MESSAGEField
            End Get
            Set
                Me.rEPLY_MESSAGEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getAccountTypeListCompletedEventHandler(ByVal sender As Object, ByVal e As getAccountTypeListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getAccountTypeListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As accountTypeWorkflow()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),accountTypeWorkflow())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getMainBankListCompletedEventHandler(ByVal sender As Object, ByVal e As getMainBankListCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getMainBankListCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As bankWorkflow()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),bankWorkflow())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getBankAccountListBySSNumberCompletedEventHandler(ByVal sender As Object, ByVal e As getBankAccountListBySSNumberCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getBankAccountListBySSNumberCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As accountNumberWorkflow()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),accountNumberWorkflow())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub insertAccountInfoCompletedEventHandler(ByVal sender As Object, ByVal e As insertAccountInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class insertAccountInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As insertAccntInfoWorkflow
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),insertAccntInfoWorkflow)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub deactivateAccInfoCompletedEventHandler(ByVal sender As Object, ByVal e As deactivateAccInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class deactivateAccInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As accountDeactiveWorkflow()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),accountDeactiveWorkflow())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub getBankAccountListByACCompletedEventHandler(ByVal sender As Object, ByVal e As getBankAccountListByACCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class getBankAccountListByACCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As accountNumberWorkflow()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),accountNumberWorkflow())
            End Get
        End Property
    End Class
End Namespace
